server:
  port: 8081
spring:
  cloud:
    config:
      server: 
        git:
          default-label: master
          uri: https://github.com/MaximusJoshep/project-1.git
          search-paths: config-data
  application:
    name: config-server
          
